apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-secret" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- range $k, $v := .Values.secret }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}